### ISSUE TITLE
[ASK] How to manage community?

### ISSUE THREAD

**Issue by IhwanID** [hendisantika/ask-me-anything#1]
Halo kang hendi, saya ihwan. Sebagai Programmer yang berpengalaman me-manage beberapa komunitas, saya ingin bertanya kepada kang hendi. 

Saya dan teman-teman programmer di Majalengka sudah berkomunitas hampir setahun, tapi baru 2x mengadakan meetup. selain terkendala waktu dan tempat acara. terkadang peserta yang datang tidak sesuai dengan jumlah yang hadir, bukan lebih banyak tapi malah bisa < 50% dari peserta yang mendaftar . padahal jumlah anggota yang tercatat sampai saat ini sudah menyentuh angka 91. 

Maka dari itu, bisakah kang hendi berbagi tips tips dalam me-manage komunitas IT supaya kami bisa lebih berkembang untuk kedepan nya?

**Comment by hendisantika** [comment]
Halo @IhwanID, manage group atau komunitas emang gampang2 susah.
Perlu ketabahan dan kesabaran dalam menghadapinya.
Kemudian masalah kehadiran para member selalu tidak 100% itu adalah masalah klasik. Kita tidak bisa mengharapkan peserta itu 100% hadir semuanya dari jumlah RSVP di event kita.

Kemudian untuk mengatasi masalah sedikitnya member komunitas kita. Maka alangkah lebih baik kita ikut dulu ke group induknya. Misalkan grup saya adalah JVM Indonesia. Daripada dibuat perdaerah, saya lebih menyarankan supaya orang2 yg di daerah yg masih sedikit membernya supaya ikut kita dulu.

Nanti kalau sudah banyak baru jalan sendiri.

Kurang lebih seperti itu.

Mudah2 bisa menjawab.

Syukron
